version: '3.8'

services:
  radio:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./music:/app/music
    restart: unless-stopped
